# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package (R CMD INSTALL or devtools::install).
# nolint start
# nocov start

# Internal helper: re-raise a tagged Rust error/condition value as an R condition.
# Generated wrappers call this whenever `.Call()` returns a `rust_condition_value`.
# `.call_default` is the wrapper's `sys.call()` (or its caller-derived
# `.mx_call` for `#[miniextendr(noexport, call = caller)]` entry points), used as the
# fallback when the Rust panic payload didn't carry a captured call (e.g.
# lambda contexts that pass `.call = NULL` to `.Call`). For error/panic kinds `stop()` longjmps;
# for warning/message/condition the helper signals and returns invisible(NULL),
# which the wrapper's surrounding `return(...)` propagates as its result.
.miniextendr_raise_condition <- function(.val, .call_default) {
  .msg <- .val$error
  .call <- (if (is.null(.val$call)) .call_default else .val$call)
  .class <- .val$class
  # `.val$data` is an optional named list of structured fields (from the
  # macros' `data = ...` form). When present, splice its named elements into
  # the condition object alongside message/call/kind so handlers can read
  # `e$<name>`. `utils::modifyList` keeps the base fields and appends the
  # data fields; a malformed (non-list / unnamed) payload is ignored.
  .data <- .val$data
  .cond_fields <- function(base) {
    if (is.null(.data) || !is.list(.data) || is.null(names(.data))) {
      base
    } else {
      utils::modifyList(base, .data)
    }
  }
  switch(.val$kind,
    error = stop(structure(.cond_fields(list(message = .msg, call = .call, kind = "error")),
      class = c(.class, "rust_error", "simpleError", "error", "condition"))),
    warning = warning(structure(.cond_fields(list(message = .msg, call = .call, kind = "warning")),
      class = c(.class, "rust_warning", "simpleWarning", "warning", "condition"))),
    message = message(structure(.cond_fields(list(message = paste0(.msg, "\n"), call = NULL, kind = "message")),
      class = c(.class, "rust_message", "simpleMessage", "message", "condition"))),
    condition = signalCondition(structure(.cond_fields(list(message = .msg, call = .call, kind = "condition")),
      class = c(.class, "rust_condition", "simpleCondition", "condition"))),
    panic = stop(structure(list(message = .msg, call = .call, kind = "panic"),
      class = c("rust_error", "simpleError", "error", "condition"))),
    # result_err / none_err / conversion / other: an error whose class vector and
    # data (if any) come from the Rust side, e.g. a `Result<T, E: RConditionError>`.
    stop(structure(.cond_fields(list(message = .msg, call = .call, kind = .val$kind)),
      class = c(.class, "rust_error", "simpleError", "error", "condition")))
  )
  invisible(NULL)
}

# Internal helper: strict `match.arg(several.ok = TRUE)` for `several_ok` params.
# Base R keeps only the elements that match as long as one of them does, so a
# misspelled entry silently shortens the selection and the per-element check on
# the Rust side never sees it (#1472). Here every element has to match a choice
# (exactly or as a unique prefix), the first that does not is reported with its
# position, and `NULL` selects every choice, like an omitted argument does. The
# error is attributed to the wrapper's own call, not to this helper.
.miniextendr_match_arg_several <- function(arg, choices, arg_name) {
  if (is.null(arg)) return(choices)
  .call <- sys.call(-1L)
  if (!is.character(arg)) stop(simpleError(sprintf("'%s' must be NULL or a character vector", arg_name), .call))
  if (length(arg) == 0L) stop(simpleError(sprintf("'%s' must be of length >= 1", arg_name), .call))
  i <- pmatch(arg, choices, nomatch = 0L, duplicates.ok = TRUE)
  bad <- which(is.na(i) | i == 0L)
  if (length(bad)) {
    stop(simpleError(sprintf("'%s' element %d (\"%s\") should be one of %s", arg_name, bad[[1L]], arg[[bad[[1L]]]], paste(dQuote(choices, FALSE), collapse = ", ")), .call))
  }
  choices[i]
}

# Generated from Rust impl `SharedData` (lib.rs:40:6)
#' @rdname SharedData
#' @title SharedData (Env-style)
#' @name SharedData
#' @description A point with label using Env-style class system.
#' @source Generated by miniextendr from Rust type `SharedData`
#' @export
SharedData <- new.env(parent = emptyenv())

# SharedData::get_x (47:8)
#' @description Get the x coordinate
#' @name SharedData$get_x
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_x`
SharedData$get_x <- function() {
  .val <- .Call(C_producer_pkg_SharedData__get_x, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# SharedData::get_y (52:8)
#' @description Get the y coordinate
#' @name SharedData$get_y
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_y`
SharedData$get_y <- function() {
  .val <- .Call(C_producer_pkg_SharedData__get_y, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# SharedData::get_label (57:8)
#' @description Get the label
#' @name SharedData$get_label
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::get_label`
SharedData$get_label <- function() {
  .val <- .Call(C_producer_pkg_SharedData__get_label, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# SharedData::create (42:8)
#' @description Create a new SharedData
#' @name SharedData$create
#' @rdname SharedData
#' @source Generated by miniextendr from `SharedData::create`
SharedData$create <- function(x, y, label) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L,
    "'label' must be character" = is.character(label),
    "'label' must have length 1" = length(label) == 1L
  )
  .val <- .Call(C_producer_pkg_SharedData__create, .call = match.call(), x, y, label)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  class(.val) <- "SharedData"
  .val
}

#' @rdname SharedData
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.SharedData` <- function(self, name) {
  obj <- SharedData[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(SharedData)) {
      ns <- SharedData[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname SharedData
#' @export
`[[.SharedData` <- `$.SharedData`

# Generated from Rust impl `EnvPoint` (lib.rs:73:6)
#' @rdname EnvPoint
#' @title EnvPoint (Env-style)
#' @name EnvPoint
#' @description A 2D point using the default Env-style class system.
#' @source Generated by miniextendr from Rust type `EnvPoint`
#' @export
EnvPoint <- new.env(parent = emptyenv())

# EnvPoint::new (75:8)
#' @description Create a new point
#' @name EnvPoint$new
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::new`
EnvPoint$new <- function(x, y) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L
  )
  .val <- .Call(C_producer_pkg_EnvPoint__new, .call = match.call(), x, y)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  self <- .val
  class(self) <- "EnvPoint"
  self
}

# EnvPoint::x (80:8)
#' @description Get x coordinate
#' @name EnvPoint$x
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::x`
EnvPoint$x <- function() {
  .val <- .Call(C_producer_pkg_EnvPoint__x, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# EnvPoint::y (85:8)
#' @description Get y coordinate
#' @name EnvPoint$y
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::y`
EnvPoint$y <- function() {
  .val <- .Call(C_producer_pkg_EnvPoint__y, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# EnvPoint::distance_from_origin (90:8)
#' @description Calculate distance from origin
#' @name EnvPoint$distance_from_origin
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::distance_from_origin`
EnvPoint$distance_from_origin <- function() {
  .val <- .Call(C_producer_pkg_EnvPoint__distance_from_origin, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# EnvPoint::add (95:8)
#' @description Add another point's coordinates
#' @name EnvPoint$add
#' @rdname EnvPoint
#' @source Generated by miniextendr from `EnvPoint::add`
EnvPoint$add <- function(dx, dy) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_producer_pkg_EnvPoint__add, .call = match.call(), self, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  self
}

#' @rdname EnvPoint
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.EnvPoint` <- function(self, name) {
  obj <- EnvPoint[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(EnvPoint)) {
      ns <- EnvPoint[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname EnvPoint
#' @export
`[[.EnvPoint` <- `$.EnvPoint`

# Generated from Rust impl `R6Point` (lib.rs:115:6)
#' @rdname R6Point
#' @title R6Point (R6-style)
#' @name R6Point
#' @description A 2D point using R6-style class system.
#' @source Generated by miniextendr from Rust type `R6Point`
#' @importFrom R6 R6Class
#' @param .ptr Internal pointer (used by static methods, not for direct use).
#' @export
R6Point <- R6::R6Class("R6Point",
  public = list(
    # R6Point::new (119:12)
    #' @description Create a new point
    #' @param x X coordinate.
    #' @param y Y coordinate.
    initialize = function(x, y, .ptr = NULL) {
      if (is.null(.ptr)) {
        stopifnot(
          "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
          "'x' must have length 1" = length(x) == 1L,
          "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
          "'y' must have length 1" = length(y) == 1L
        )
      }
      if (!is.null(.ptr)) {
        private$.ptr <- .ptr
      } else {
        .val <- .Call(C_producer_pkg_R6Point__new, .call = match.call(), x, y)
        if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
        private$.ptr <- .val
      }
    }
  ),
  private = list(
    .ptr = NULL
  ),
  lock_objects = TRUE,
  lock_class = FALSE,
  cloneable = FALSE
)

# R6Point::x (124:12)
#' @description Get x coordinate
R6Point$set("public", "x", function() {
  .val <- .Call(C_producer_pkg_R6Point__x, .call = match.call(), private$.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
})

# R6Point::y (129:12)
#' @description Get y coordinate
R6Point$set("public", "y", function() {
  .val <- .Call(C_producer_pkg_R6Point__y, .call = match.call(), private$.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
})

# R6Point::distance_from_origin (134:12)
#' @description Calculate distance from origin
R6Point$set("public", "distance_from_origin", function() {
  .val <- .Call(C_producer_pkg_R6Point__distance_from_origin, .call = match.call(), private$.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
})

# R6Point::add (141:12)
#' @description Add to coordinates
#' @param dx Amount to add to x.
#' @param dy Amount to add to y.
R6Point$set("public", "add", function(dx, dy) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_producer_pkg_R6Point__add, .call = match.call(), private$.ptr, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(self)
})

# Generated from Rust impl `S3Point` (lib.rs:162:6)
# S3Point::new (164:12)
#' @rdname S3Point
#' @title S3Point (S3-style)
#' @name S3Point
#' @description A 2D point using S3-style class system.
#' @aliases new_s3point s3point_x s3point_y s3point_distance
#' @description Create a new point
#' @source Generated by miniextendr from Rust type `S3Point`
#' @export
new_s3point <- function(x, y) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L
  )
  .val <- .Call(C_producer_pkg_S3Point__new, .call = match.call(), x, y)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  structure(.val, class = "S3Point")
}

# S3Point::s3point_x (169:12)
#' @title S3 generic for `s3point_x`
#' @description S3 generic for `s3point_x`
#' @name s3point_x.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_x`
#' @export s3point_x
if (!base::exists("s3point_x", mode = "function")) {
  s3point_x <- function(x, ...) UseMethod("s3point_x")
} else if (local({ .mx_gen <- base::get("s3point_x", mode = "function"); !(is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s3point_x") || inherits(.mx_gen, "S7_generic")) })) {
  # `s3point_x` is a plain closure that UseMethod dispatch will never consult.
  # Shadow it with a package-local generic. The default method delegating to
  # the masked closure is registered via registerS3method() so it lives ONLY
  # in the namespace's S3 methods table: a literal `s3point_x.default` binding
  # would trip roxygen2's dynamic S3 scan (warn_missing_s3_exports), and a
  # static NAMESPACE S3method(s3point_x, default) would break package load
  # whenever this branch does not fire.
  .mx_shadow_default <- local({
    .mx_masked <- base::get("s3point_x", mode = "function")
    function(x, ...) .mx_masked(x, ...)
  })
  s3point_x <- function(x, ...) UseMethod("s3point_x")
  base::registerS3method("s3point_x", "default", .mx_shadow_default, envir = base::environment())
  base::rm(.mx_shadow_default)
}
# else: existing usable generic (primitive/S3/S4/S7) — reuse as-is.

#' @description Get x coordinate
#' @name s3point_x.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_x`
#' @method s3point_x S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_x.S3Point <- function(x, ...) {
  .val <- .Call(C_producer_pkg_S3Point__s3point_x, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# S3Point::s3point_y (174:12)
#' @title S3 generic for `s3point_y`
#' @description S3 generic for `s3point_y`
#' @name s3point_y.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_y`
#' @export s3point_y
if (!base::exists("s3point_y", mode = "function")) {
  s3point_y <- function(x, ...) UseMethod("s3point_y")
} else if (local({ .mx_gen <- base::get("s3point_y", mode = "function"); !(is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s3point_y") || inherits(.mx_gen, "S7_generic")) })) {
  # `s3point_y` is a plain closure that UseMethod dispatch will never consult.
  # Shadow it with a package-local generic. The default method delegating to
  # the masked closure is registered via registerS3method() so it lives ONLY
  # in the namespace's S3 methods table: a literal `s3point_y.default` binding
  # would trip roxygen2's dynamic S3 scan (warn_missing_s3_exports), and a
  # static NAMESPACE S3method(s3point_y, default) would break package load
  # whenever this branch does not fire.
  .mx_shadow_default <- local({
    .mx_masked <- base::get("s3point_y", mode = "function")
    function(x, ...) .mx_masked(x, ...)
  })
  s3point_y <- function(x, ...) UseMethod("s3point_y")
  base::registerS3method("s3point_y", "default", .mx_shadow_default, envir = base::environment())
  base::rm(.mx_shadow_default)
}
# else: existing usable generic (primitive/S3/S4/S7) — reuse as-is.

#' @description Get y coordinate
#' @name s3point_y.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_y`
#' @method s3point_y S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_y.S3Point <- function(x, ...) {
  .val <- .Call(C_producer_pkg_S3Point__s3point_y, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# S3Point::s3point_distance (179:12)
#' @title S3 generic for `s3point_distance`
#' @description S3 generic for `s3point_distance`
#' @name s3point_distance.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_distance`
#' @export s3point_distance
if (!base::exists("s3point_distance", mode = "function")) {
  s3point_distance <- function(x, ...) UseMethod("s3point_distance")
} else if (local({ .mx_gen <- base::get("s3point_distance", mode = "function"); !(is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s3point_distance") || inherits(.mx_gen, "S7_generic")) })) {
  # `s3point_distance` is a plain closure that UseMethod dispatch will never consult.
  # Shadow it with a package-local generic. The default method delegating to
  # the masked closure is registered via registerS3method() so it lives ONLY
  # in the namespace's S3 methods table: a literal `s3point_distance.default` binding
  # would trip roxygen2's dynamic S3 scan (warn_missing_s3_exports), and a
  # static NAMESPACE S3method(s3point_distance, default) would break package load
  # whenever this branch does not fire.
  .mx_shadow_default <- local({
    .mx_masked <- base::get("s3point_distance", mode = "function")
    function(x, ...) .mx_masked(x, ...)
  })
  s3point_distance <- function(x, ...) UseMethod("s3point_distance")
  base::registerS3method("s3point_distance", "default", .mx_shadow_default, envir = base::environment())
  base::rm(.mx_shadow_default)
}
# else: existing usable generic (primitive/S3/S4/S7) — reuse as-is.

#' @description Calculate distance from origin
#' @name s3point_distance.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_distance`
#' @method s3point_distance S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_distance.S3Point <- function(x, ...) {
  .val <- .Call(C_producer_pkg_S3Point__s3point_distance, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# S3Point::s3point_add (184:12)
#' @title S3 generic for `s3point_add`
#' @description S3 generic for `s3point_add`
#' @name s3point_add.S3Point
#' @rdname S3Point
#' @param x An object
#' @param ... Additional arguments passed to methods
#' @source Generated by miniextendr from `S3Point::s3point_add`
#' @export s3point_add
if (!base::exists("s3point_add", mode = "function")) {
  s3point_add <- function(x, ...) UseMethod("s3point_add")
} else if (local({ .mx_gen <- base::get("s3point_add", mode = "function"); !(is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s3point_add") || inherits(.mx_gen, "S7_generic")) })) {
  # `s3point_add` is a plain closure that UseMethod dispatch will never consult.
  # Shadow it with a package-local generic. The default method delegating to
  # the masked closure is registered via registerS3method() so it lives ONLY
  # in the namespace's S3 methods table: a literal `s3point_add.default` binding
  # would trip roxygen2's dynamic S3 scan (warn_missing_s3_exports), and a
  # static NAMESPACE S3method(s3point_add, default) would break package load
  # whenever this branch does not fire.
  .mx_shadow_default <- local({
    .mx_masked <- base::get("s3point_add", mode = "function")
    function(x, ...) .mx_masked(x, ...)
  })
  s3point_add <- function(x, ...) UseMethod("s3point_add")
  base::registerS3method("s3point_add", "default", .mx_shadow_default, envir = base::environment())
  base::rm(.mx_shadow_default)
}
# else: existing usable generic (primitive/S3/S4/S7) — reuse as-is.

#' @description Add to coordinates
#' @param dx (undocumented)
#' @param dy (undocumented)
#' @name s3point_add.S3Point
#' @rdname S3Point
#' @source Generated by miniextendr from `S3Point::s3point_add`
#' @method s3point_add S3Point
#' @param x An object.
#' @param ... Additional arguments.
#' @export
s3point_add.S3Point <- function(x, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_producer_pkg_S3Point__s3point_add, .call = match.call(), x, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  x
}

#' @rdname S3Point
#' @export
S3Point <- new.env(parent = emptyenv())

S3Point$new <- new_s3point

# Generated from Rust impl `S4Point` (lib.rs:205:6)
#' @rdname S4Point
#' @title S4Point (S4-style)
#' @name S4Point
#' @description A 2D point using S4-style class system.
#' @aliases S4Point s4point_x s4point_y s4point_distance
#' @source Generated by miniextendr from Rust type `S4Point`
#' @importFrom methods setClass setGeneric setMethod new
#' @slot ptr External pointer to Rust `S4Point` struct
methods::setClass("S4Point", slots = c(ptr = "externalptr"))

# S4Point::new (207:12)
#' @description Create a new point
#' @param x (undocumented)
#' @param y (undocumented)
#' @name S4Point
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::new`
#' @export
S4Point <- function(x, y) {
  stopifnot(
    "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
    "'x' must have length 1" = length(x) == 1L,
    "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
    "'y' must have length 1" = length(y) == 1L
  )
  .val <- .Call(C_producer_pkg_S4Point__new, .call = match.call(), x, y)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  methods::new("S4Point", ptr = .val)
}

#' The `s4_x()` generic
#'
#' @description
#' `s4_x()` is an S4 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S4Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s4_x
#' @exportMethod s4_x
NULL
# S4Point::x (212:12)
#' @description Get x coordinate
#' @name S4Point-s4_x
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_x`
#' @aliases s4_x,S4Point-method
if (!exists("s4_x", where = topenv(environment()), inherits = FALSE)) methods::setGeneric("s4_x", function(x, ...) standardGeneric("s4_x"))
#' @exportMethod s4_x
methods::setMethod("s4_x", "S4Point", function(x, ...) {
  .val <- .Call(C_producer_pkg_S4Point__x, .call = match.call(), x@ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
})

#' The `s4_y()` generic
#'
#' @description
#' `s4_y()` is an S4 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S4Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s4_y
#' @exportMethod s4_y
NULL
# S4Point::y (217:12)
#' @description Get y coordinate
#' @name S4Point-s4_y
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_y`
#' @aliases s4_y,S4Point-method
if (!exists("s4_y", where = topenv(environment()), inherits = FALSE)) methods::setGeneric("s4_y", function(x, ...) standardGeneric("s4_y"))
#' @exportMethod s4_y
methods::setMethod("s4_y", "S4Point", function(x, ...) {
  .val <- .Call(C_producer_pkg_S4Point__y, .call = match.call(), x@ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
})

#' The `s4_distance()` generic
#'
#' @description
#' `s4_distance()` is an S4 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S4Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s4_distance
#' @exportMethod s4_distance
NULL
# S4Point::distance (222:12)
#' @description Calculate distance from origin
#' @name S4Point-s4_distance
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_distance`
#' @aliases s4_distance,S4Point-method
if (!exists("s4_distance", where = topenv(environment()), inherits = FALSE)) methods::setGeneric("s4_distance", function(x, ...) standardGeneric("s4_distance"))
#' @exportMethod s4_distance
methods::setMethod("s4_distance", "S4Point", function(x, ...) {
  .val <- .Call(C_producer_pkg_S4Point__distance, .call = match.call(), x@ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
})

#' The `s4_add()` generic
#'
#' @description
#' `s4_add()` is an S4 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S4Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s4_add
#' @exportMethod s4_add
NULL
# S4Point::add (227:12)
#' @description Add to coordinates
#' @name S4Point-s4_add
#' @rdname S4Point
#' @source Generated by miniextendr from `S4Point::s4_add`
#' @aliases s4_add,S4Point-method
if (!exists("s4_add", where = topenv(environment()), inherits = FALSE)) methods::setGeneric("s4_add", function(x, ...) standardGeneric("s4_add"))
#' @exportMethod s4_add
methods::setMethod("s4_add", "S4Point", function(x, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_producer_pkg_S4Point__add, .call = match.call(), x@ptr, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  x
})

# Generated from Rust impl `S7Point` (lib.rs:248:6)
#' @rdname S7Point
#' @title S7Point (S7-style)
#' @name S7Point
#' @description A 2D point using S7-style class system.
#' @aliases S7Point s7point_x s7point_y s7point_distance
#' @source Generated by miniextendr from Rust type `S7Point`
#' @importFrom S7 new_class class_any new_object S7_object new_generic method
#' @export
#' @param x (undocumented)
#' @param y (undocumented)
#' @param .ptr Internal pointer (used by static methods, not for direct use).
S7Point <- S7::new_class("S7Point",
  properties = list(
    .ptr = S7::class_any
  ),
  constructor = function(x, y, .ptr = NULL) {
    if (is.null(.ptr)) {
      stopifnot(
        "'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x),
        "'x' must have length 1" = length(x) == 1L,
        "'y' must be numeric, logical, or raw" = is.numeric(y) || is.logical(y) || is.raw(y),
        "'y' must have length 1" = length(y) == 1L
      )
    }
    if (!is.null(.ptr)) {
      S7::new_object(S7::S7_object(), .ptr = .ptr)
    } else {
      .val <- .Call(C_producer_pkg_S7Point__new, .call = match.call(), x, y)
      if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
      S7::new_object(S7::S7_object(), .ptr = .val)
    }
  }
)

#' The `s7point_x()` generic
#'
#' @description
#' `s7point_x()` is an S7 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S7Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s7point_x
#' @rawNamespace export(s7point_x)
NULL
# S7Point::s7point_x (255:12)
#' @description Get x coordinate
#' @name S7Point-s7point_x
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_x`
#' @aliases S7Point$s7point_x
#' @rawNamespace export(s7point_x)
if (!base::exists("s7point_x", mode = "function")) {
  # No existing binding; define a plain package-local S7 generic.
  s7point_x <- S7::new_generic("s7point_x", "x", function(x, ...) S7::S7_dispatch())
} else if (local({ .mx_gen <- base::get("s7point_x", mode = "function"); !(inherits(.mx_gen, "S7_generic") || is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s7point_x")) })) {
  # `s7point_x` resolves to a plain (non-generic) function S7 cannot
  # attach a method to. Define a package-local S7 generic that shadows it,
  # with a class_any fallback delegating to the masked function so ordinary
  # (non-S7) calls (e.g. var(1:10)) keep working. S4 generics also take this
  # path; the fallback preserves their dispatch.
  s7point_x <- local({
    .mx_masked <- base::get("s7point_x", mode = "function")
    .mx_g <- S7::new_generic("s7point_x", "x", function(x, ...) S7::S7_dispatch())
    S7::method(.mx_g, S7::class_any) <- function(x, ...) .mx_masked(x, ...)
    .mx_g
  })
}
# else: existing usable generic (S7/primitive/S3/S4) — reuse as-is.
S7::method(s7point_x, S7Point) <- function(x, ...) {
  .val <- .Call(C_producer_pkg_S7Point__s7point_x, .call = match.call(), x@.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' Fast-path shortcut for the `s7point_x` S7 method on `S7Point`.
#'
#' Calls the underlying Rust routine directly, bypassing `S7::S7_dispatch()`
#' (the class walk + method-table lookup). Use in hot loops where the
#' per-call dispatch overhead matters. **Footgun:** this shortcut does not
#' perform subclass dispatch — a method override defined on a child class
#' will *not* be honoured. Use the generic when subclassing is possible.
#' @param self A `S7Point` object.
#' @param ... Additional arguments; ignored by the fast-path shortcut.
#' @name S7Point_s7point_x
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_x`
#' @export S7Point_s7point_x
S7Point_s7point_x <- function(self, ...) {
  .val <- .Call(C_producer_pkg_S7Point__s7point_x, .call = match.call(), self@.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' The `s7point_y()` generic
#'
#' @description
#' `s7point_y()` is an S7 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S7Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s7point_y
#' @rawNamespace export(s7point_y)
NULL
# S7Point::s7point_y (260:12)
#' @description Get y coordinate
#' @name S7Point-s7point_y
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_y`
#' @aliases S7Point$s7point_y
#' @rawNamespace export(s7point_y)
if (!base::exists("s7point_y", mode = "function")) {
  # No existing binding; define a plain package-local S7 generic.
  s7point_y <- S7::new_generic("s7point_y", "x", function(x, ...) S7::S7_dispatch())
} else if (local({ .mx_gen <- base::get("s7point_y", mode = "function"); !(inherits(.mx_gen, "S7_generic") || is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s7point_y")) })) {
  # `s7point_y` resolves to a plain (non-generic) function S7 cannot
  # attach a method to. Define a package-local S7 generic that shadows it,
  # with a class_any fallback delegating to the masked function so ordinary
  # (non-S7) calls (e.g. var(1:10)) keep working. S4 generics also take this
  # path; the fallback preserves their dispatch.
  s7point_y <- local({
    .mx_masked <- base::get("s7point_y", mode = "function")
    .mx_g <- S7::new_generic("s7point_y", "x", function(x, ...) S7::S7_dispatch())
    S7::method(.mx_g, S7::class_any) <- function(x, ...) .mx_masked(x, ...)
    .mx_g
  })
}
# else: existing usable generic (S7/primitive/S3/S4) — reuse as-is.
S7::method(s7point_y, S7Point) <- function(x, ...) {
  .val <- .Call(C_producer_pkg_S7Point__s7point_y, .call = match.call(), x@.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' Fast-path shortcut for the `s7point_y` S7 method on `S7Point`.
#'
#' Calls the underlying Rust routine directly, bypassing `S7::S7_dispatch()`
#' (the class walk + method-table lookup). Use in hot loops where the
#' per-call dispatch overhead matters. **Footgun:** this shortcut does not
#' perform subclass dispatch — a method override defined on a child class
#' will *not* be honoured. Use the generic when subclassing is possible.
#' @param self A `S7Point` object.
#' @param ... Additional arguments; ignored by the fast-path shortcut.
#' @name S7Point_s7point_y
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_y`
#' @export S7Point_s7point_y
S7Point_s7point_y <- function(self, ...) {
  .val <- .Call(C_producer_pkg_S7Point__s7point_y, .call = match.call(), self@.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' The `s7point_distance()` generic
#'
#' @description
#' `s7point_distance()` is an S7 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S7Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s7point_distance
#' @rawNamespace export(s7point_distance)
NULL
# S7Point::s7point_distance (265:12)
#' @description Calculate distance from origin
#' @name S7Point-s7point_distance
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_distance`
#' @aliases S7Point$s7point_distance
#' @rawNamespace export(s7point_distance)
if (!base::exists("s7point_distance", mode = "function")) {
  # No existing binding; define a plain package-local S7 generic.
  s7point_distance <- S7::new_generic("s7point_distance", "x", function(x, ...) S7::S7_dispatch())
} else if (local({ .mx_gen <- base::get("s7point_distance", mode = "function"); !(inherits(.mx_gen, "S7_generic") || is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s7point_distance")) })) {
  # `s7point_distance` resolves to a plain (non-generic) function S7 cannot
  # attach a method to. Define a package-local S7 generic that shadows it,
  # with a class_any fallback delegating to the masked function so ordinary
  # (non-S7) calls (e.g. var(1:10)) keep working. S4 generics also take this
  # path; the fallback preserves their dispatch.
  s7point_distance <- local({
    .mx_masked <- base::get("s7point_distance", mode = "function")
    .mx_g <- S7::new_generic("s7point_distance", "x", function(x, ...) S7::S7_dispatch())
    S7::method(.mx_g, S7::class_any) <- function(x, ...) .mx_masked(x, ...)
    .mx_g
  })
}
# else: existing usable generic (S7/primitive/S3/S4) — reuse as-is.
S7::method(s7point_distance, S7Point) <- function(x, ...) {
  .val <- .Call(C_producer_pkg_S7Point__s7point_distance, .call = match.call(), x@.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' Fast-path shortcut for the `s7point_distance` S7 method on `S7Point`.
#'
#' Calls the underlying Rust routine directly, bypassing `S7::S7_dispatch()`
#' (the class walk + method-table lookup). Use in hot loops where the
#' per-call dispatch overhead matters. **Footgun:** this shortcut does not
#' perform subclass dispatch — a method override defined on a child class
#' will *not* be honoured. Use the generic when subclassing is possible.
#' @param self A `S7Point` object.
#' @param ... Additional arguments; ignored by the fast-path shortcut.
#' @name S7Point_s7point_distance
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_distance`
#' @export S7Point_s7point_distance
S7Point_s7point_distance <- function(self, ...) {
  .val <- .Call(C_producer_pkg_S7Point__s7point_distance, .call = match.call(), self@.ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' The `s7point_add()` generic
#'
#' @description
#' `s7point_add()` is an S7 generic generated by miniextendr. Methods in this
#' package are available for:
#' \itemize{
#'   \item \code{\link{S7Point}}
#' }
#' @param x An object.
#' @param ... Passed on to methods.
#' @name s7point_add
#' @rawNamespace export(s7point_add)
NULL
# S7Point::s7point_add (270:12)
#' @description Add to coordinates
#' @name S7Point-s7point_add
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_add`
#' @aliases S7Point$s7point_add
#' @rawNamespace export(s7point_add)
if (!base::exists("s7point_add", mode = "function")) {
  # No existing binding; define a plain package-local S7 generic.
  s7point_add <- S7::new_generic("s7point_add", "x", function(x, ...) S7::S7_dispatch())
} else if (local({ .mx_gen <- base::get("s7point_add", mode = "function"); !(inherits(.mx_gen, "S7_generic") || is.primitive(.mx_gen) || isTRUE(utils::isS3stdGeneric(.mx_gen)) || methods::isGeneric("s7point_add")) })) {
  # `s7point_add` resolves to a plain (non-generic) function S7 cannot
  # attach a method to. Define a package-local S7 generic that shadows it,
  # with a class_any fallback delegating to the masked function so ordinary
  # (non-S7) calls (e.g. var(1:10)) keep working. S4 generics also take this
  # path; the fallback preserves their dispatch.
  s7point_add <- local({
    .mx_masked <- base::get("s7point_add", mode = "function")
    .mx_g <- S7::new_generic("s7point_add", "x", function(x, ...) S7::S7_dispatch())
    S7::method(.mx_g, S7::class_any) <- function(x, ...) .mx_masked(x, ...)
    .mx_g
  })
}
# else: existing usable generic (S7/primitive/S3/S4) — reuse as-is.
S7::method(s7point_add, S7Point) <- function(x, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_producer_pkg_S7Point__s7point_add, .call = match.call(), x@.ptr, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  x
}

#' Fast-path shortcut for the `s7point_add` S7 method on `S7Point`.
#'
#' Calls the underlying Rust routine directly, bypassing `S7::S7_dispatch()`
#' (the class walk + method-table lookup). Use in hot loops where the
#' per-call dispatch overhead matters. **Footgun:** this shortcut does not
#' perform subclass dispatch — a method override defined on a child class
#' will *not* be honoured. Use the generic when subclassing is possible.
#' @param self A `S7Point` object.
#' @param ... Additional arguments; ignored by the fast-path shortcut.
#' @param dx (undocumented)
#' @param dy (undocumented)
#' @name S7Point_s7point_add
#' @rdname S7Point
#' @source Generated by miniextendr from `S7Point::s7point_add`
#' @export S7Point_s7point_add
S7Point_s7point_add <- function(self, dx, dy, ...) {
  stopifnot(
    "'dx' must be numeric, logical, or raw" = is.numeric(dx) || is.logical(dx) || is.raw(dx),
    "'dx' must have length 1" = length(dx) == 1L,
    "'dy' must be numeric, logical, or raw" = is.numeric(dy) || is.logical(dy) || is.raw(dy),
    "'dy' must have length 1" = length(dy) == 1L
  )
  .val <- .Call(C_producer_pkg_S7Point__s7point_add, .call = match.call(), self@.ptr, dx, dy)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  self
}

# Generated from Rust impl `SimpleCounter` (lib.rs:291:6)
#' @title SimpleCounter  Class
#' @name SimpleCounter
#' @rdname SimpleCounter
#' @source Generated by miniextendr from Rust type `SimpleCounter`
#' @export
SimpleCounter <- new.env(parent = emptyenv())

# SimpleCounter::get_value (293:8)
#' @description Get current value (inherent method)
#' @name SimpleCounter$get_value
#' @rdname SimpleCounter
#' @source Generated by miniextendr from `SimpleCounter::get_value`
SimpleCounter$get_value <- function() {
  .val <- .Call(C_producer_pkg_SimpleCounter__get_value, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' @rdname SimpleCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.SimpleCounter` <- function(self, name) {
  obj <- SimpleCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(SimpleCounter)) {
      ns <- SimpleCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname SimpleCounter
#' @export
`[[.SimpleCounter` <- `$.SimpleCounter`

# Generated from Rust impl `StatefulCounter` (lib.rs:396:6)
#' @title StatefulCounter  Class
#' @name StatefulCounter
#' @rdname StatefulCounter
#' @source Generated by miniextendr from Rust type `StatefulCounter`
#' @export
StatefulCounter <- new.env(parent = emptyenv())

# StatefulCounter::get_value (398:8)
#' @description Get current value (inherent method)
#' @name StatefulCounter$get_value
#' @rdname StatefulCounter
#' @source Generated by miniextendr from `StatefulCounter::get_value`
StatefulCounter$get_value <- function() {
  .val <- .Call(C_producer_pkg_StatefulCounter__get_value, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# StatefulCounter::history_len (403:8)
#' @description Get how many history entries exist
#' @name StatefulCounter$history_len
#' @rdname StatefulCounter
#' @source Generated by miniextendr from `StatefulCounter::history_len`
StatefulCounter$history_len <- function() {
  .val <- .Call(C_producer_pkg_StatefulCounter__history_len, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

#' @rdname StatefulCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.StatefulCounter` <- function(self, name) {
  obj <- StatefulCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(StatefulCounter)) {
      ns <- StatefulCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname StatefulCounter
#' @export
`[[.StatefulCounter` <- `$.StatefulCounter`

# Generated from Rust fn `new_stateful_counter` (lib.rs:488:8)
#' @title new_stateful_counter
#' @description Create a new StatefulCounter with cross-package trait dispatch support
#' @param initial Initial counter value
#' @return An external pointer to the wrapped stateful counter
#' @export
#' @source Generated by miniextendr from Rust fn `new_stateful_counter`
new_stateful_counter <- function(initial) {
  stopifnot(
    "'initial' must be numeric, logical, or raw" = is.numeric(initial) || is.logical(initial) || is.raw(initial),
    "'initial' must have length 1" = length(initial) == 1L
  )
  .val <- .Call(C_producer_pkg_new_stateful_counter, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_counter` (lib.rs:499:8)
#' @title new_counter
#' @description Create a new counter with cross-package trait dispatch support
#' @param initial Initial counter value
#' @return An external pointer to the wrapped counter
#' @export
#' @source Generated by miniextendr from Rust fn `new_counter`
new_counter <- function(initial) {
  stopifnot(
    "'initial' must be numeric, logical, or raw" = is.numeric(initial) || is.logical(initial) || is.raw(initial),
    "'initial' must have length 1" = length(initial) == 1L
  )
  .val <- .Call(C_producer_pkg_new_counter, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `counter_get_value` (lib.rs:510:8)
#' @title counter_get_value
#' @description Get the value from a trait-wrapped counter
#' @param counter_sexp An external pointer from new_counter()
#' @return The counter's current value
#' @export
#' @source Generated by miniextendr from Rust fn `counter_get_value`
counter_get_value <- function(counter_sexp) {
  .val <- .Call(C_producer_pkg_counter_get_value, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_tag_counter` (lib.rs:522:8)
#' @title debug_tag_counter
#' @description Debug: Get TAG_COUNTER as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_tag_counter`
debug_tag_counter <- function() {
  .val <- .Call(C_producer_pkg_debug_tag_counter, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_tag_resettable` (lib.rs:529:8)
#' @title debug_tag_resettable
#' @description Debug: Get TAG_RESETTABLE as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_tag_resettable`
debug_tag_resettable <- function() {
  .val <- .Call(C_producer_pkg_debug_tag_resettable, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_shared_data_type_name` (lib.rs:536:8)
#' @title debug_shared_data_type_name
#' @description Debug: Get the ExternalPtr type name for SharedData
#' @export
#' @source Generated by miniextendr from Rust fn `debug_shared_data_type_name`
debug_shared_data_type_name <- function() {
  .val <- .Call(C_producer_pkg_debug_shared_data_type_name, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `get_r_class` (lib.rs:546:8)
#' @title get_r_class
#' @description Get class of any R object (for cross-package testing)
#' @param x Any R object
#' @return Character vector of class names
#' @export
#' @source Generated by miniextendr from Rust fn `get_r_class`
get_r_class <- function(x) {
  .val <- .Call(C_producer_pkg_get_r_class, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_temperature` (lib.rs:597:8)
#' @title new_temperature
#' @description Create a `producer_temp` vctrs vector (Celsius temperatures).
#' 
#' This is the exported constructor consumer.pkg imports via `importFrom(producer.pkg, new_temperature)` to build a producer-owned vctrs type. Dispatch (format/coercion/`vec_c`) then resolves through R's S3 method registry once producer.pkg is loaded.
#' @param x Numeric temperatures in Celsius.
#' @return A `producer_temp` vctrs vector.
#' @export
#' @source Generated by miniextendr from Rust fn `new_temperature`
new_temperature <- function(x) {
  stopifnot("'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x))
  .val <- .Call(C_producer_pkg_new_temperature, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_oven_temperature` (lib.rs:638:8)
#' @title new_oven_temperature
#' @description Create a `producer_oven_temp` vctrs vector that inherits from `producer_temp`.
#' 
#' Exercises `extends` (#1039): the child inherits the parent's format/abbr S3 methods through the class vector, and coercion between the two resolves to the parent (the supertype). consumer.pkg imports this constructor to verify inheritance dispatches across the package boundary.
#' @param x Numeric oven temperatures in Celsius.
#' @return A `producer_oven_temp` vctrs vector inheriting from `producer_temp`.
#' @export
#' @source Generated by miniextendr from Rust fn `new_oven_temperature`
new_oven_temperature <- function(x) {
  stopifnot("'x' must be numeric, logical, or raw" = is.numeric(x) || is.logical(x) || is.raw(x))
  .val <- .Call(C_producer_pkg_new_oven_temperature, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust impl `Counter` for `SimpleCounter` (lib.rs:299:18)
# Trait methods and consts for SimpleCounter implementing Counter
# Generated by #[miniextendr] impl Counter for SimpleCounter

SimpleCounter$Counter <- new.env(parent = emptyenv())

#' @name SimpleCounter$Counter$value
#' @rdname SimpleCounter
SimpleCounter$Counter$value <- function(x) {
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__value, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}
attr(SimpleCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$increment
#' @rdname SimpleCounter
SimpleCounter$Counter$increment <- function(x) {
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__increment, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$add
#' @rdname SimpleCounter
SimpleCounter$Counter$add <- function(x, n) {
  stopifnot(
    "'n' must be numeric, logical, or raw" = is.numeric(n) || is.logical(n) || is.raw(n),
    "'n' must have length 1" = length(n) == 1L
  )
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__add, .call = match.call(), x, n)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$add, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$panic_plain
#' @rdname SimpleCounter
SimpleCounter$Counter$panic_plain <- function(x) {
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__panic_plain, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$panic_plain, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$error_with_class
#' @rdname SimpleCounter
SimpleCounter$Counter$error_with_class <- function(x, class_name) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L
  )
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__error_with_class, .call = match.call(), x, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$error_with_class, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$raise_error
#' @rdname SimpleCounter
SimpleCounter$Counter$raise_error <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__raise_error, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$raise_error, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$raise_warning
#' @rdname SimpleCounter
SimpleCounter$Counter$raise_warning <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__raise_warning, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$raise_warning, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$raise_message
#' @rdname SimpleCounter
SimpleCounter$Counter$raise_message <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__raise_message, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$raise_message, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$raise_condition_classed
#' @rdname SimpleCounter
SimpleCounter$Counter$raise_condition_classed <- function(x, class_name, msg) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L,
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__raise_condition_classed, .call = match.call(), x, class_name, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$raise_condition_classed, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Counter$raise_error_with_data
#' @rdname SimpleCounter
SimpleCounter$Counter$raise_error_with_data <- function(x) {
  .val <- .Call(C_producer_pkg_SimpleCounter__Counter__raise_error_with_data, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Counter$raise_error_with_data, ".__mx_instance__") <- TRUE

# Generated from Rust impl `Resettable` for `SimpleCounter` (lib.rs:367:21)
# Trait methods and consts for SimpleCounter implementing Resettable
# Generated by #[miniextendr] impl Resettable for SimpleCounter

SimpleCounter$Resettable <- new.env(parent = emptyenv())

#' @name SimpleCounter$Resettable$reset
#' @rdname SimpleCounter
SimpleCounter$Resettable$reset <- function(x) {
  .val <- .Call(C_producer_pkg_SimpleCounter__Resettable__reset, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(SimpleCounter$Resettable$reset, ".__mx_instance__") <- TRUE

#' @name SimpleCounter$Resettable$is_default
#' @rdname SimpleCounter
SimpleCounter$Resettable$is_default <- function(x) {
  .val <- .Call(C_producer_pkg_SimpleCounter__Resettable__is_default, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}
attr(SimpleCounter$Resettable$is_default, ".__mx_instance__") <- TRUE

# Generated from Rust impl `Counter` for `StatefulCounter` (lib.rs:409:18)
# Trait methods and consts for StatefulCounter implementing Counter
# Generated by #[miniextendr] impl Counter for StatefulCounter

StatefulCounter$Counter <- new.env(parent = emptyenv())

#' @name StatefulCounter$Counter$value
#' @rdname StatefulCounter
StatefulCounter$Counter$value <- function(x) {
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__value, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}
attr(StatefulCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$increment
#' @rdname StatefulCounter
StatefulCounter$Counter$increment <- function(x) {
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__increment, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$add
#' @rdname StatefulCounter
StatefulCounter$Counter$add <- function(x, n) {
  stopifnot(
    "'n' must be numeric, logical, or raw" = is.numeric(n) || is.logical(n) || is.raw(n),
    "'n' must have length 1" = length(n) == 1L
  )
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__add, .call = match.call(), x, n)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$add, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$panic_plain
#' @rdname StatefulCounter
StatefulCounter$Counter$panic_plain <- function(x) {
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__panic_plain, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$panic_plain, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$error_with_class
#' @rdname StatefulCounter
StatefulCounter$Counter$error_with_class <- function(x, class_name) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L
  )
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__error_with_class, .call = match.call(), x, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$error_with_class, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$raise_error
#' @rdname StatefulCounter
StatefulCounter$Counter$raise_error <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__raise_error, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$raise_error, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$raise_warning
#' @rdname StatefulCounter
StatefulCounter$Counter$raise_warning <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__raise_warning, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$raise_warning, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$raise_message
#' @rdname StatefulCounter
StatefulCounter$Counter$raise_message <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__raise_message, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$raise_message, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$raise_condition_classed
#' @rdname StatefulCounter
StatefulCounter$Counter$raise_condition_classed <- function(x, class_name, msg) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L,
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__raise_condition_classed, .call = match.call(), x, class_name, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$raise_condition_classed, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Counter$raise_error_with_data
#' @rdname StatefulCounter
StatefulCounter$Counter$raise_error_with_data <- function(x) {
  .val <- .Call(C_producer_pkg_StatefulCounter__Counter__raise_error_with_data, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Counter$raise_error_with_data, ".__mx_instance__") <- TRUE

# Generated from Rust impl `Resettable` for `StatefulCounter` (lib.rs:471:21)
# Trait methods and consts for StatefulCounter implementing Resettable
# Generated by #[miniextendr] impl Resettable for StatefulCounter

StatefulCounter$Resettable <- new.env(parent = emptyenv())

#' @name StatefulCounter$Resettable$reset
#' @rdname StatefulCounter
StatefulCounter$Resettable$reset <- function(x) {
  .val <- .Call(C_producer_pkg_StatefulCounter__Resettable__reset, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(StatefulCounter$Resettable$reset, ".__mx_instance__") <- TRUE

#' @name StatefulCounter$Resettable$is_default
#' @rdname StatefulCounter
StatefulCounter$Resettable$is_default <- function(x) {
  .val <- .Call(C_producer_pkg_StatefulCounter__Resettable__is_default, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}
attr(StatefulCounter$Resettable$is_default, ".__mx_instance__") <- TRUE

# Generated from Rust derive(Vctrs) on `ProducerTemp` (lib.rs:580:12)
#' @export
format.producer_temp <- function(x, ...) {
  format(unclass(x), ...)
}

#' @importFrom vctrs vec_ptype_abbr
#' @export
vec_ptype_abbr.producer_temp <- function(x, ...) {
  "degC"
}

#' @importFrom vctrs vec_ptype_full
#' @export
vec_ptype_full.producer_temp <- function(x, ...) {
  "producer_temp"
}

#' @importFrom vctrs vec_proxy
#' @export
vec_proxy.producer_temp <- function(x, ...) {
  unclass(x)
}

#' @importFrom vctrs vec_restore new_vctr
#' @export
vec_restore.producer_temp <- function(x, to, ...) {
  vctrs::new_vctr(x, class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_ptype2 new_vctr
#' @export
vec_ptype2.producer_temp.producer_temp <- function(x, y, ...) {
  vctrs::new_vctr(double(0), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_cast
#' @export
vec_cast.producer_temp.producer_temp <- function(x, to, ...) {
  x
}

#' @importFrom vctrs vec_ptype2 new_vctr
#' @export
vec_ptype2.producer_temp.double <- function(x, y, ...) {
  vctrs::new_vctr(double(0), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_ptype2 new_vctr
#' @export
vec_ptype2.double.producer_temp <- function(x, y, ...) {
  vctrs::new_vctr(double(0), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_cast new_vctr
#' @export
vec_cast.producer_temp.double <- function(x, to, ...) {
  vctrs::new_vctr(as.double(x), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_cast vec_data
#' @export
vec_cast.double.producer_temp <- function(x, to, ...) {
  vctrs::vec_data(x)
}

# Generated from Rust derive(Vctrs) on `ProducerOvenTemp` (lib.rs:621:12)
#' @export
format.producer_oven_temp <- function(x, ...) {
  format(unclass(x), ...)
}

#' @importFrom vctrs vec_ptype_full
#' @export
vec_ptype_full.producer_oven_temp <- function(x, ...) {
  "producer_oven_temp"
}

#' @importFrom vctrs vec_proxy
#' @export
vec_proxy.producer_oven_temp <- function(x, ...) {
  unclass(x)
}

#' @importFrom vctrs vec_restore new_vctr
#' @export
vec_restore.producer_oven_temp <- function(x, to, ...) {
  vctrs::new_vctr(x, class = c("producer_oven_temp", "producer_temp"), inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_ptype2 new_vctr
#' @export
vec_ptype2.producer_oven_temp.producer_oven_temp <- function(x, y, ...) {
  vctrs::new_vctr(double(0), class = c("producer_oven_temp", "producer_temp"), inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_cast
#' @export
vec_cast.producer_oven_temp.producer_oven_temp <- function(x, to, ...) {
  x
}

#' @importFrom vctrs vec_ptype2 new_vctr
#' @export
vec_ptype2.producer_oven_temp.producer_temp <- function(x, y, ...) {
  vctrs::new_vctr(double(0), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_ptype2 new_vctr
#' @export
vec_ptype2.producer_temp.producer_oven_temp <- function(x, y, ...) {
  vctrs::new_vctr(double(0), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_cast new_vctr vec_data
#' @export
vec_cast.producer_temp.producer_oven_temp <- function(x, to, ...) {
  vctrs::new_vctr(vctrs::vec_data(x), class = "producer_temp", inherit_base_type = FALSE)
}

#' @importFrom vctrs vec_cast new_vctr vec_data
#' @export
vec_cast.producer_oven_temp.producer_temp <- function(x, to, ...) {
  vctrs::new_vctr(vctrs::vec_data(x), class = c("producer_oven_temp", "producer_temp"), inherit_base_type = FALSE)
}

# nocov end
# nolint end
