# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package (R CMD INSTALL or devtools::install).
# nolint start
# nocov start

# Internal helper: re-raise a tagged Rust error/condition value as an R condition.
# Generated wrappers call this whenever `.Call()` returns a `rust_condition_value`.
# `.call_default` is the wrapper's `sys.call()` (or its caller-derived
# `.mx_call` for `#[miniextendr(noexport, call = caller)]` entry points), used as the
# fallback when the Rust panic payload didn't carry a captured call (e.g.
# lambda contexts that pass `.call = NULL` to `.Call`). For error/panic kinds `stop()` longjmps;
# for warning/message/condition the helper signals and returns invisible(NULL),
# which the wrapper's surrounding `return(...)` propagates as its result.
.miniextendr_raise_condition <- function(.val, .call_default) {
  .msg <- .val$error
  .call <- (if (is.null(.val$call)) .call_default else .val$call)
  .class <- .val$class
  # `.val$data` is an optional named list of structured fields (from the
  # macros' `data = ...` form). When present, splice its named elements into
  # the condition object alongside message/call/kind so handlers can read
  # `e$<name>`. `utils::modifyList` keeps the base fields and appends the
  # data fields; a malformed (non-list / unnamed) payload is ignored.
  .data <- .val$data
  .cond_fields <- function(base) {
    if (is.null(.data) || !is.list(.data) || is.null(names(.data))) {
      base
    } else {
      utils::modifyList(base, .data)
    }
  }
  switch(.val$kind,
    error = stop(structure(.cond_fields(list(message = .msg, call = .call, kind = "error")),
      class = c(.class, "rust_error", "simpleError", "error", "condition"))),
    warning = warning(structure(.cond_fields(list(message = .msg, call = .call, kind = "warning")),
      class = c(.class, "rust_warning", "simpleWarning", "warning", "condition"))),
    message = message(structure(.cond_fields(list(message = paste0(.msg, "\n"), call = NULL, kind = "message")),
      class = c(.class, "rust_message", "simpleMessage", "message", "condition"))),
    condition = signalCondition(structure(.cond_fields(list(message = .msg, call = .call, kind = "condition")),
      class = c(.class, "rust_condition", "simpleCondition", "condition"))),
    panic = stop(structure(list(message = .msg, call = .call, kind = "panic"),
      class = c("rust_error", "simpleError", "error", "condition"))),
    # result_err / none_err / conversion / other: an error whose class vector and
    # data (if any) come from the Rust side, e.g. a `Result<T, E: RConditionError>`.
    stop(structure(.cond_fields(list(message = .msg, call = .call, kind = .val$kind)),
      class = c(.class, "rust_error", "simpleError", "error", "condition")))
  )
  invisible(NULL)
}

# Internal helper: strict `match.arg(several.ok = TRUE)` for `several_ok` params.
# Base R keeps only the elements that match as long as one of them does, so a
# misspelled entry silently shortens the selection and the per-element check on
# the Rust side never sees it (#1472). Here every element has to match a choice
# (exactly or as a unique prefix), the first that does not is reported with its
# position, and `NULL` selects every choice, like an omitted argument does. The
# error is attributed to the wrapper's own call, not to this helper.
.miniextendr_match_arg_several <- function(arg, choices, arg_name) {
  if (is.null(arg)) return(choices)
  .call <- sys.call(-1L)
  if (!is.character(arg)) stop(simpleError(sprintf("'%s' must be NULL or a character vector", arg_name), .call))
  if (length(arg) == 0L) stop(simpleError(sprintf("'%s' must be of length >= 1", arg_name), .call))
  i <- pmatch(arg, choices, nomatch = 0L, duplicates.ok = TRUE)
  bad <- which(is.na(i) | i == 0L)
  if (length(bad)) {
    stop(simpleError(sprintf("'%s' element %d (\"%s\") should be one of %s", arg_name, bad[[1L]], arg[[bad[[1L]]]], paste(dQuote(choices, FALSE), collapse = ", ")), .call))
  }
  choices[i]
}

# Generated from Rust impl `DoubleCounter` (lib.rs:84:6)
#' @title DoubleCounter  Class
#' @name DoubleCounter
#' @rdname DoubleCounter
#' @source Generated by miniextendr from Rust type `DoubleCounter`
#' @export
DoubleCounter <- new.env(parent = emptyenv())

# DoubleCounter::get_value (90:8)
#' @description Get the current value (inherent method)
#' @name DoubleCounter$get_value
#' @rdname DoubleCounter
#' @source Generated by miniextendr from `DoubleCounter::get_value`
DoubleCounter$get_value <- function() {
  .val <- .Call(C_consumer_pkg_DoubleCounter__get_value, .call = match.call(), self)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# DoubleCounter::create (85:8)
#' @name DoubleCounter$create
#' @rdname DoubleCounter
#' @source Generated by miniextendr from `DoubleCounter::create`
DoubleCounter$create <- function(initial) {
  stopifnot(
    "'initial' must be numeric, logical, or raw" = is.numeric(initial) || is.logical(initial) || is.raw(initial),
    "'initial' must have length 1" = length(initial) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__create, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  class(.val) <- "DoubleCounter"
  .val
}

#' @rdname DoubleCounter
#' @param self The object instance.
#' @param name Method name for dispatch.
#' @export
`$.DoubleCounter` <- function(self, name) {
  obj <- DoubleCounter[[name]]
  if (is.environment(obj)) {
    # Trait namespace - wrap instance methods to prepend self
    bound <- new.env(parent = emptyenv())
    for (method_name in names(obj)) {
      method <- obj[[method_name]]
      if (is.function(method)) {
        if (isTRUE(attr(method, ".__mx_instance__"))) {
          local({
            m <- method
            bound[[method_name]] <<- function(...) m(self, ...)
          })
        } else {
          bound[[method_name]] <- method
        }
      }
    }
    bound
  } else if (is.null(obj)) {
    # Not found at top level -- search trait namespace environments
    for (ns_name in names(DoubleCounter)) {
      ns <- DoubleCounter[[ns_name]]
      if (is.environment(ns) && exists(name, envir = ns, inherits = FALSE)) {
        method <- ns[[name]]
        if (is.function(method) && isTRUE(attr(method, ".__mx_instance__"))) {
          # Instance method -- bind self as first arg
          m <- method
          s <- self
          return(function(...) m(s, ...))
        } else if (is.function(method)) {
          return(method)
        }
      }
    }
    NULL
  } else {
    environment(obj) <- environment()
    obj
  }
}
#' @rdname DoubleCounter
#' @export
`[[.DoubleCounter` <- `$.DoubleCounter`

# Generated from Rust fn `passthrough_ptr` (lib.rs:29:8)
#' @title passthrough_ptr
#' @description Pass an ExternalPtr through consumer without knowing its type. This tests that ExternalPtr can cross package boundaries as opaque SEXP.
#' @param ptr An ExternalPtr from any package
#' @return The same ExternalPtr (pass-through)
#' @export
#' @source Generated by miniextendr from Rust fn `passthrough_ptr`
passthrough_ptr <- function(ptr) {
  .val <- .Call(C_consumer_pkg_passthrough_ptr, .call = match.call(), ptr)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `is_external_ptr` (lib.rs:38:8)
#' @title is_external_ptr
#' @description Check if a SEXP is an ExternalPtr (type-agnostic check)
#' @param sexp Any R object
#' @return TRUE if it's an ExternalPtr
#' @export
#' @source Generated by miniextendr from Rust fn `is_external_ptr`
is_external_ptr <- function(sexp) {
  .val <- .Call(C_consumer_pkg_is_external_ptr, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `consumer_get_class` (lib.rs:48:8)
#' @title consumer_get_class
#' @description Get class of any R object (for cross-package testing)
#' @param x Any R object
#' @return Character vector of class names
#' @export
#' @source Generated by miniextendr from Rust fn `consumer_get_class`
consumer_get_class <- function(x) {
  .val <- .Call(C_consumer_pkg_consumer_get_class, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `has_class` (lib.rs:58:8)
#' @title has_class
#' @description Check if an object has a specific class
#' @param x Any R object
#' @param class_name Class name to check for
#' @return TRUE if object has the specified class
#' @export
#' @source Generated by miniextendr from Rust fn `has_class`
has_class <- function(x, class_name) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L
  )
  .val <- .Call(C_consumer_pkg_has_class, .call = match.call(), x, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `new_double_counter` (lib.rs:161:8)
#' @title new_double_counter
#' @description Create a new DoubleCounter (consumer's own Counter implementation) DoubleCounter increments by 2, demonstrating a different implementation.
#' @param initial Initial counter value
#' @return An external pointer to the wrapped DoubleCounter
#' @export
#' @source Generated by miniextendr from Rust fn `new_double_counter`
new_double_counter <- function(initial) {
  stopifnot(
    "'initial' must be numeric, logical, or raw" = is.numeric(initial) || is.logical(initial) || is.raw(initial),
    "'initial' must have length 1" = length(initial) == 1L
  )
  .val <- .Call(C_consumer_pkg_new_double_counter, .call = match.call(), initial)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `increment_twice` (lib.rs:176:8)
#' @title increment_twice
#' @description Increment a counter twice (generic over Counter trait) This function works with Counter objects from ANY package.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @return The counter's value after incrementing twice
#' @export
#' @source Generated by miniextendr from Rust fn `increment_twice`
increment_twice <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_increment_twice, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `add_and_get` (lib.rs:189:8)
#' @title add_and_get
#' @description Add a value to a counter and return the new value
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param n Value to add
#' @return The counter's value after adding n
#' @export
#' @source Generated by miniextendr from Rust fn `add_and_get`
add_and_get <- function(counter_sexp, n) {
  stopifnot(
    "'n' must be numeric, logical, or raw" = is.numeric(n) || is.logical(n) || is.raw(n),
    "'n' must have length 1" = length(n) == 1L
  )
  .val <- .Call(C_consumer_pkg_add_and_get, .call = match.call(), counter_sexp, n)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `peek_value` (lib.rs:200:8)
#' @title peek_value
#' @description Get value without modifying (uses immutable reference)
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @return The counter's current value
#' @export
#' @source Generated by miniextendr from Rust fn `peek_value`
peek_value <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_peek_value, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `is_counter` (lib.rs:210:8)
#' @title is_counter
#' @description Check if an object implements the Counter trait
#' @param sexp Any R object
#' @return TRUE if the object implements Counter trait
#' @export
#' @source Generated by miniextendr from Rust fn `is_counter`
is_counter <- function(sexp) {
  .val <- .Call(C_consumer_pkg_is_counter, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `reset_and_check` (lib.rs:223:8)
#' @title reset_and_check
#' @description Reset an object and check if it's in default state This function works with Resettable objects from ANY package.
#' @param sexp An ExternalPtr to any type implementing Resettable
#' @return TRUE if the object is in default state after reset
#' @export
#' @source Generated by miniextendr from Rust fn `reset_and_check`
reset_and_check <- function(sexp) {
  .val <- .Call(C_consumer_pkg_reset_and_check, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `check_is_default` (lib.rs:234:8)
#' @title check_is_default
#' @description Check if an object is in its default state (without resetting)
#' @param sexp An ExternalPtr to any type implementing Resettable
#' @return TRUE if the object is in default state
#' @export
#' @source Generated by miniextendr from Rust fn `check_is_default`
check_is_default <- function(sexp) {
  .val <- .Call(C_consumer_pkg_check_is_default, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `is_resettable` (lib.rs:244:8)
#' @title is_resettable
#' @description Check if an object implements the Resettable trait
#' @param sexp Any R object
#' @return TRUE if the object implements Resettable trait
#' @export
#' @source Generated by miniextendr from Rust fn `is_resettable`
is_resettable <- function(sexp) {
  .val <- .Call(C_consumer_pkg_is_resettable, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `increment_then_reset` (lib.rs:257:8)
#' @title increment_then_reset
#' @description Increment a Counter twice, then reset it via Resettable, return is_default Tests combined trait usage on the same object across packages.
#' @param sexp An ExternalPtr to a type implementing BOTH Counter and Resettable
#' @return TRUE if the object is in default state after increment+reset
#' @export
#' @source Generated by miniextendr from Rust fn `increment_then_reset`
increment_then_reset <- function(sexp) {
  .val <- .Call(C_consumer_pkg_increment_then_reset, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `get_reset_get` (lib.rs:275:8)
#' @title get_reset_get
#' @description Get the value of a Counter, reset it, then get the value again Returns the value after reset.
#' @param sexp An ExternalPtr to a type implementing BOTH Counter and Resettable
#' @return The counter value after reset
#' @export
#' @source Generated by miniextendr from Rust fn `get_reset_get`
get_reset_get <- function(sexp) {
  .val <- .Call(C_consumer_pkg_get_reset_get, .call = match.call(), sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_consumer_tag_resettable` (lib.rs:288:8)
#' @title debug_consumer_tag_resettable
#' @description Debug: Get TAG_RESETTABLE as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_consumer_tag_resettable`
debug_consumer_tag_resettable <- function() {
  .val <- .Call(C_consumer_pkg_debug_consumer_tag_resettable, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `counter_panic_plain` (lib.rs:302:8)
#' @title counter_panic_plain
#' @description Call panic_plain() on any Counter object via trait dispatch.
#' 
#' Used by spike tests to verify rust_error class layering across the trait-ABI boundary.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @export
#' @source Generated by miniextendr from Rust fn `counter_panic_plain`
counter_panic_plain <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_counter_panic_plain, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_error_with_class` (lib.rs:315:8)
#' @title counter_error_with_class
#' @description Call error_with_class() on any Counter object via trait dispatch.
#' 
#' Used by spike tests to verify user-class layering across the trait-ABI boundary.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param class_name The class name to use with error!()
#' @export
#' @source Generated by miniextendr from Rust fn `counter_error_with_class`
counter_error_with_class <- function(counter_sexp, class_name) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L
  )
  .val <- .Call(C_consumer_pkg_counter_error_with_class, .call = match.call(), counter_sexp, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_error` (lib.rs:329:8)
#' @title counter_raise_error
#' @description Raise a bare error!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `error!()` round-trips to `rust_error` / `e$kind == "error"` across the trait-ABI boundary, matching the in-process matrix's free-fn / R6 error rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param msg The error message
#' @export
#' @source Generated by miniextendr from Rust fn `counter_raise_error`
counter_raise_error <- function(counter_sexp, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_counter_raise_error, .call = match.call(), counter_sexp, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_warning` (lib.rs:343:8)
#' @title counter_raise_warning
#' @description Raise a warning!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `warning!()` round-trips to `rust_warning` / `e$kind == "warning"` across the trait-ABI boundary, matching the in-process matrix's R6/S3/S4/S7 warning rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param msg The warning message
#' @export
#' @source Generated by miniextendr from Rust fn `counter_raise_warning`
counter_raise_warning <- function(counter_sexp, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_counter_raise_warning, .call = match.call(), counter_sexp, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_message` (lib.rs:357:8)
#' @title counter_raise_message
#' @description Raise a message!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `message!()` round-trips to `rust_message` / `e$kind == "message"` across the trait-ABI boundary, matching the in-process matrix's message rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param msg The message body
#' @export
#' @source Generated by miniextendr from Rust fn `counter_raise_message`
counter_raise_message <- function(counter_sexp, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_counter_raise_message, .call = match.call(), counter_sexp, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_condition_classed` (lib.rs:373:8)
#' @title counter_raise_condition_classed
#' @description Raise a classed condition!() through a Counter trait method via trait dispatch.
#' 
#' Verifies that a producer-side `condition!(class = …)` is catchable by the user class and round-trips to `e$kind == "condition"` across the trait-ABI boundary, matching the in-process matrix's condition!() rows.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @param class_name The class name to use with condition!()
#' @param msg The condition message
#' @export
#' @source Generated by miniextendr from Rust fn `counter_raise_condition_classed`
counter_raise_condition_classed <- function(counter_sexp, class_name, msg) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L,
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_counter_raise_condition_classed, .call = match.call(), counter_sexp, class_name, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `counter_raise_error_with_data` (lib.rs:391:8)
#' @title counter_raise_error_with_data
#' @description Raise an error!() with structured `data =` fields through a Counter trait method via trait dispatch.
#' 
#' Exercises the `from_tagged_sexp` slot 4 round-trip path (issue #996 path-1): producer raises `error!(class = "data_bearing_error", data = [...], "msg")`, the vtable shim returns a tagged SEXP, `repanic_if_rust_error` reconstructs the `RCondition` (including data), and the consumer's `with_r_unwind_protect` guard re-emits a new tagged SEXP with the data intact.
#' 
#' R handlers can then access `e$field_a`, `e$field_b`, `e$flag`, `e$score`.
#' @param counter_sexp An ExternalPtr to any type implementing Counter
#' @export
#' @source Generated by miniextendr from Rust fn `counter_raise_error_with_data`
counter_raise_error_with_data <- function(counter_sexp) {
  .val <- .Call(C_consumer_pkg_counter_raise_error_with_data, .call = match.call(), counter_sexp)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  invisible(.val)
}

# Generated from Rust fn `consumer_greet` (lib.rs:405:8)
#' @title consumer_greet
#' @description Greet with a message demonstrating consumer package is working
#' @param name Name to greet
#' @return A greeting string
#' @export
#' @source Generated by miniextendr from Rust fn `consumer_greet`
consumer_greet <- function(name) {
  stopifnot(
    "'name' must be character" = is.character(name),
    "'name' must have length 1" = length(name) == 1L
  )
  .val <- .Call(C_consumer_pkg_consumer_greet, .call = match.call(), name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `consumer_magic_number` (lib.rs:413:8)
#' @title consumer_magic_number
#' @description Return a constant to verify the package is loaded
#' @return The number 42
#' @export
#' @source Generated by miniextendr from Rust fn `consumer_magic_number`
consumer_magic_number <- function() {
  .val <- .Call(C_consumer_pkg_consumer_magic_number, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust fn `debug_consumer_tag_counter` (lib.rs:420:8)
#' @title debug_consumer_tag_counter
#' @description Debug: Get TAG_COUNTER as hex string
#' @export
#' @source Generated by miniextendr from Rust fn `debug_consumer_tag_counter`
debug_consumer_tag_counter <- function() {
  .val <- .Call(C_consumer_pkg_debug_consumer_tag_counter, .call = match.call())
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}

# Generated from Rust impl `Counter` for `DoubleCounter` (lib.rs:96:18)
# Trait methods and consts for DoubleCounter implementing Counter
# Generated by #[miniextendr] impl Counter for DoubleCounter

DoubleCounter$Counter <- new.env(parent = emptyenv())

#' @name DoubleCounter$Counter$value
#' @rdname DoubleCounter
DoubleCounter$Counter$value <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__value, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
}
attr(DoubleCounter$Counter$value, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$increment
#' @rdname DoubleCounter
DoubleCounter$Counter$increment <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__increment, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$increment, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$add
#' @rdname DoubleCounter
DoubleCounter$Counter$add <- function(x, n) {
  stopifnot(
    "'n' must be numeric, logical, or raw" = is.numeric(n) || is.logical(n) || is.raw(n),
    "'n' must have length 1" = length(n) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__add, .call = match.call(), x, n)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$add, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$panic_plain
#' @rdname DoubleCounter
DoubleCounter$Counter$panic_plain <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__panic_plain, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$panic_plain, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$error_with_class
#' @rdname DoubleCounter
DoubleCounter$Counter$error_with_class <- function(x, class_name) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__error_with_class, .call = match.call(), x, class_name)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$error_with_class, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_error
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_error <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_error, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$raise_error, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_warning
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_warning <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_warning, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$raise_warning, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_message
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_message <- function(x, msg) {
  stopifnot(
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_message, .call = match.call(), x, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$raise_message, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_condition_classed
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_condition_classed <- function(x, class_name, msg) {
  stopifnot(
    "'class_name' must be character" = is.character(class_name),
    "'class_name' must have length 1" = length(class_name) == 1L,
    "'msg' must be character" = is.character(msg),
    "'msg' must have length 1" = length(msg) == 1L
  )
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_condition_classed, .call = match.call(), x, class_name, msg)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$raise_condition_classed, ".__mx_instance__") <- TRUE

#' @name DoubleCounter$Counter$raise_error_with_data
#' @rdname DoubleCounter
DoubleCounter$Counter$raise_error_with_data <- function(x) {
  .val <- .Call(C_consumer_pkg_DoubleCounter__Counter__raise_error_with_data, .call = match.call(), x)
  if (inherits(.val, "rust_condition_value") && isTRUE(attr(.val, "__rust_condition__"))) return(.miniextendr_raise_condition(.val, sys.call()))
  .val
  invisible(x)
}
attr(DoubleCounter$Counter$raise_error_with_data, ".__mx_instance__") <- TRUE

# nocov end
# nolint end
