# match_arg / choices / several_ok on impl-block methods (issue #153).
#
# Companion to test-match-arg.R (standalone fns) — exercises the same
# validation surface on methods generated by the r6, env, s7, s3, and
# vctrs class-system generators.

# region: R6 — scalar match_arg on constructor + instance method

test_that("R6 constructor default picks first choice", {
  c <- R6MatchArgCounter$new()
  expect_equal(c$mode(), "Fast")
})

test_that("R6 constructor accepts exact + partial match", {
  expect_equal(R6MatchArgCounter$new("Safe")$mode(), "Safe")
  expect_equal(R6MatchArgCounter$new("D")$mode(), "Debug")
})

test_that("R6 instance match_arg method validates argument", {
  c <- R6MatchArgCounter$new("Fast")
  expect_equal(c$record("Safe"), 1L)
  expect_equal(c$mode(), "Safe")
  expect_equal(c$record("D"), 2L)
  expect_equal(c$mode(), "Debug")
})

test_that("R6 constructor rejects non-choice", {
  expect_error(R6MatchArgCounter$new("Invalid"), "should be one of")
})

test_that("R6 static method with explicit choices()", {
  expect_equal(R6MatchArgCounter$describe_level(), "level=low")
  expect_equal(R6MatchArgCounter$describe_level("medium"), "level=medium")
  expect_equal(R6MatchArgCounter$describe_level("hi"), "level=high")
  expect_error(
    R6MatchArgCounter$describe_level("bogus"),
    "should be one of"
  )
})

# endregion

# region: env — several_ok container on constructor + instance method

test_that("env constructor accepts a vector of choices (several_ok)", {
  e <- EnvMatchArgCounter$new(c("Fast", "Safe"))
  expect_equal(e$count(), 2L)
})

test_that("env constructor default — several.ok returns the full choice list", {
  # `match.arg(c("Fast","Safe","Debug"), choices, several.ok = TRUE)` matches
  # every element exactly, so the formal default round-trips the full vector.
  e <- EnvMatchArgCounter$new()
  expect_equal(e$count(), 3L)
})

test_that("env instance reset accepts multi-value choices", {
  e <- EnvMatchArgCounter$new("Fast")
  expect_equal(e$reset(c("Safe", "Debug", "Fast")), 3L)
})

test_that("env several_ok rejects an all-invalid vector", {
  expect_error(
    EnvMatchArgCounter$new(c("Bogus", "Other")),
    "should be one of"
  )
})

test_that("env several_ok rejects a partially invalid vector (#1472)", {
  # base match.arg(several.ok = TRUE) would have kept "Fast" and dropped
  # "Bogus" silently; the strict prelude names the offending element.
  expect_error(
    EnvMatchArgCounter$new(c("Fast", "Bogus")),
    "'modes' element 2 \\(\"Bogus\"\\) should be one of"
  )
  e <- EnvMatchArgCounter$new("Fast")
  expect_error(e$reset(c("Bogus", "Safe")), "'modes' element 1")
  expect_equal(e$count(), 1L)
})

test_that("env several_ok: NULL selects every choice", {
  expect_equal(EnvMatchArgCounter$new(NULL)$count(), 3L)
})

# endregion

# region: S7 — scalar match_arg on method + constructor

test_that("S7 constructor validates match_arg", {
  h <- S7MatchArgHolder(mode = "Safe")
  expect_equal(current(h), "Safe")
})

test_that("S7 set() generic validates match_arg", {
  h <- S7MatchArgHolder(mode = "Fast")
  expect_equal(set(h, "Debug"), "Debug")
  expect_equal(current(h), "Debug")
})

test_that("S7 constructor rejects non-choice", {
  expect_error(S7MatchArgHolder(mode = "Bogus"), "should be one of")
})

test_that("S7 fast-path shortcut carries match_arg validation (#949)", {
  h <- S7MatchArgHolder(mode = "Fast")
  # Exported shortcut agrees with the generic.
  expect_equal(S7MatchArgHolder_current(h), current(h))
  # Shortcut validates and applies match_arg, mutating in place.
  expect_equal(S7MatchArgHolder_set(h, "Debug"), "Debug")
  expect_equal(S7MatchArgHolder_current(h), "Debug")
  # Partial matching still works through the shortcut.
  expect_equal(S7MatchArgHolder_set(h, "Sa"), "Safe")
  # Invalid choices are rejected by match.arg in the shortcut.
  expect_error(S7MatchArgHolder_set(h, "Bogus"), "should be one of")
})

# endregion

# region: S3 — choices() on constructor + match_arg on instance method

test_that("S3 constructor with choices() formal default", {
  p <- new_s3matchargpoint()
  expect_equal(label(p), "alpha")
})

test_that("S3 constructor validates choices", {
  expect_equal(label(new_s3matchargpoint("beta")), "beta")
  expect_error(new_s3matchargpoint("nope"), "should be one of")
})

test_that("S3 instance method with match_arg validates", {
  p <- new_s3matchargpoint("alpha")
  expect_equal(relabel(p, "Safe"), "alpha-Safe")
})

test_that("S3 instance method with Option<T> match_arg: NULL means no choice (#1473)", {
  p <- new_s3matchargpoint("beta")
  expect_equal(maybe_relabel(p), "beta")
  expect_equal(maybe_relabel(p, NULL), "beta")
  expect_equal(maybe_relabel(p, "Sa"), "beta-Safe")
  expect_error(maybe_relabel(p, "nope"), "should be one of")
})

test_that("S3MatchArgPoint class object constructs via $new", {
  p <- S3MatchArgPoint$new("gamma")
  expect_true(inherits(p, "S3MatchArgPoint"))
  expect_equal(label(p), "gamma")
})

# endregion

# region: S4 — scalar match_arg on constructor + instance method (#209)

test_that("S4 constructor default picks first choice", {
  h <- S4MatchArgHolder()
  expect_equal(s4_mode_current(h), "Fast")
})

test_that("S4 constructor accepts exact + partial match", {
  expect_equal(s4_mode_current(S4MatchArgHolder("Safe")), "Safe")
  expect_equal(s4_mode_current(S4MatchArgHolder("D")), "Debug")
})

test_that("S4 instance setter validates match_arg", {
  h <- S4MatchArgHolder("Fast")
  expect_equal(s4_mode_set(h, "Debug"), "Debug")
  expect_equal(s4_mode_current(h), "Debug")
})

test_that("S4 constructor rejects non-choice", {
  expect_error(S4MatchArgHolder("Bogus"), "should be one of")
})

# endregion

# region: vctrs — scalar match_arg on constructor (#208)

test_that("vctrs constructor default picks first choice", {
  v <- new_vctrsmatchargscale()
  expect_s3_class(v, "VctrsMatchArgScale")
  expect_s3_class(v, "vctrs_vctr")
})

test_that("vctrs constructor accepts exact + partial match", {
  expect_s3_class(new_vctrsmatchargscale("Safe"), "VctrsMatchArgScale")
  expect_s3_class(new_vctrsmatchargscale("D"), "VctrsMatchArgScale")
})

test_that("vctrs constructor rejects non-choice", {
  expect_error(new_vctrsmatchargscale("Bogus"), "should be one of")
})

test_that("vctrs abbr appears in ptype_abbr", {
  v <- new_vctrsmatchargscale("Safe")
  expect_equal(vctrs::vec_ptype_abbr(v), "mode")
})

# endregion
